# -*- coding: utf-8 -*-
"""DL1_boston.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10M_I2fZjwFsPrgVLT-rzkwidzEwmxRme
"""

# Assignment 1: Linear Regression using Deep Neural Network
# Boston Housing Price Prediction using CSV Dataset

# Step 1: Import Necessary Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Input

# Step 2: Load CSV Dataset
# df = pd.read_csv("C:/Users/Admin/Downloads/boston_housing.csv")
from google.colab import files

uploaded = files.upload()

# Step 2: Load CSV Dataset
df = pd.read_csv("boston_housing.csv")

# Display First 5 Rows
print(df.head())

# Step 3: Features and Target
# MEDV = House Price (Target Variable)

X = df.drop("MEDV", axis=1)
y = df["MEDV"]

print("\nFeature Shape:", X.shape)
print("Target Shape :", y.shape)

# Step 4: Split Dataset into Train and Test
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Step 5: Feature Scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Step 6: Build Deep Neural Network Model
model = Sequential([

    Input(shape=(X_train.shape[1],)),

    Dense(128, activation='relu'),
    Dropout(0.2),

    Dense(64, activation='relu'),
    Dropout(0.2),

    Dense(32, activation='relu'),

    Dense(1, activation='linear')
])

# Step 7: Compile Model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

# Step 8: Display Model Summary
model.summary()

# Step 9: Train Model
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=8,
    validation_split=0.05,
    verbose=1
)

# Step 10: Evaluate Model
loss, mae = model.evaluate(X_test, y_test)

print("\nTest Loss (MSE):", loss)
print("Test MAE:", mae)

# Step 11: Predictions
y_pred = model.predict(X_test)

print("\nActual vs Predicted Values:\n")

for i in range(10):
    print("Actual:", y_test.iloc[i], "Predicted:", y_pred[i][0])

# Step 12: Calculate Evaluation Metrics
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\nEvaluation Metrics")
print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R2 Score:", r2)

# Step 13: Predict House Price for New Data
# Boston dataset contains 13 features

new_data = np.array([[
    0.1,    # CRIM
    18.0,   # ZN
    2.31,   # INDUS
    0.0,    # CHAS
    0.5,    # NOX
    6.5,    # RM
    65.0,   # AGE
    4.0,    # DIS
    1.0,    # RAD
    300.0,  # TAX
    15.0,   # PTRATIO
    390.0,  # B
    5.0     # LSTAT
]])

# Scale New Data
new_data_scaled = scaler.transform(new_data)

# Predict Price
prediction = model.predict(new_data_scaled)

print("\nPredicted House Price:", prediction[0][0])

# Step 14: Plot Training and Validation Loss
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.title("Training vs Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()

plt.show()


import seaborn as sns
# Correlation Heatmap

plt.figure(figsize=(10,8))

sns.heatmap(df.corr(), annot=True, cmap='coolwarm')

plt.title("Feature Correlation Heatmap")

plt.show()

plt.plot(history.history['loss'])

plt.title("Training Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")

plt.show()

plt.plot(y_test.values[:20], label='Actual')
plt.plot(y_pred[:20], label='Predicted')

plt.title("Actual vs Predicted")
plt.xlabel("Samples")
plt.ylabel("Price")

plt.legend()
plt.show()