# -*- coding: utf-8 -*-
"""Classification using deep neural network..ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qKpYx9RXLLtEJHyuKvkquIaNHTO0yf0J

Practical: Classification using Deep neural network (Any One from the following):
1. Multiclass classification using Deep Neural Networks: Example: Use the OCR letter
recognition datasethttps://archive.ics.uci.edu/ml/datasets/letter+recognition
2. Binary classification using Deep Neural Networks Example: Classify movie reviews into
positive" reviews and "negative" reviews, just based on the text content of the reviews.
Use IMDB dataset
"""

import numpy as np, pandas as pd, matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

url = "https://archive.ics.uci.edu/ml/machine-learning-databases" + "/letter-recognition/letter-recognition.data"

df = pd.read_csv(url, header=None)

X = df.iloc[:, 1:]
X = X / 15.0
y = df.iloc[:, 0]
y = pd.get_dummies(y)
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.3, random_state=42
)

model = Sequential([
Dense(64, input_dim=16, activation='relu'),
Dense(32, activation='relu'), Dense(26, activation='softmax')
])

model.compile(
loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']
)

history = model.fit(
X_train, y_train, validation_data=(X_test, y_test), epochs=100, batch_size=32
)

test_loss, test_acc = model.evaluate(X_test, y_test)
print("Test accuracy:", test_acc)
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs = range(1, len(acc) + 1)
plt.figure(figsize=(10, 5))

# Plot training and validation Accuracy & Loss
plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.plot(epochs, loss, 'bo', label='Training loss',color='red')
plt.plot(epochs, val_loss, 'b', label='Validation loss',color='red')
plt.title('Training and validation'), plt.xlabel('Epochs')
plt.ylabel('Accuracy/Loss'), plt.legend(), plt.show()

# Make predictions on test data
y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)
y_true = np.argmax(np.array(y_test), axis=1)

# Calculate prediction accuracy
test_acc = np.mean(y_pred == y_true), print("Test accuracy:", test_acc)

# Create a confusion matrix
conf_mat = np.zeros((26, 26), dtype=int)
for i in range(len(y_true)):
    conf_mat[y_true[i], y_pred[i]] += 1

# Visualize prediction accuracy
plt.figure(figsize=(10, 10))
plt.imshow(conf_mat, cmap='Oranges')
plt.xticks(range(26), [chr(ord('A')+i) for i in range(26)])
plt.yticks(range(26), [chr(ord('A')+i) for i in range(26)])
plt.xlabel('Predicted label')
plt.ylabel('Actual label')
plt.title('Confusion matrix')
for i in range(26):
    for j in range(26):
        plt.text(
            j, i, conf_mat[i, j], ha='center', va='center',
            color='white' if conf_mat[i, j] > len(y_true)*0.05 else 'black'
        )
plt.show()

from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load the dataset
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)

# Pad the sequences to the same length
X_train = pad_sequences(X_train, maxlen=100)
X_test = pad_sequences(X_test, maxlen=100)

from keras.layers import Embedding, Conv1D, MaxPooling1D, GlobalMaxPooling1D

maxlen = 100 # Defining maxlen based on previous pad_sequences call
bmodel = Sequential([
Embedding(input_dim=10000, output_dim=32),
Conv1D(32, 7, activation='relu'), MaxPooling1D(5),
Conv1D(32, 7, activation='relu'), GlobalMaxPooling1D(),
Dense(1, activation='sigmoid')
])
bmodel.compile(
optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc']
)

history = bmodel.fit(
X_train, y_train, epochs=16, batch_size=128, validation_split=0.2
)

score = bmodel.evaluate(X_test, y_test)
print("Test loss:", score[0])
print("Test accuracy:", score[1])
acc = history.history['acc']
val_acc = history.history['val_acc']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs = range(1, len(acc) + 1)

# Plot the training and validation accuracy & loss
plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.plot(epochs, loss, 'bo', label='Training loss', color='red')
plt.plot(epochs, val_loss, 'b', label='Validation Loss', color='red')
plt.title('Training and validation accuracy')
plt.xlabel('Epochs'), plt.ylabel('Accuracy'), plt.legend(), plt.show()