# -*- coding: utf-8 -*-
"""Recurrent neural network (RNN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1FKI6chR2drrKWg5FavuRmPUvRJsj2H

Practical: Recurrent neural network (RNN) Use the Google stock prices dataset and design a time series analysis and prediction system using RNN.
"""

# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Dropout

# Load dataset
df = pd.read_csv('GOOG.csv', index_col='Date', parse_dates=['Date'])

# Keep only Close column
df = df[['Close']]
print(df.head())

# Normalize data
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(df['Close'].values.reshape(-1, 1))

# Training data length (80%)
training_data_len = int(np.ceil(len(scaled_data) * 0.8))

# Prepare training data
train_data = scaled_data[0:training_data_len]

x_train = []
y_train = []

for i in range(60, len(train_data)):
    x_train.append(train_data[i-60:i, 0])
    y_train.append(train_data[i, 0])

# Convert to numpy arrays
x_train = np.array(x_train)
y_train = np.array(y_train)

# Reshape for LSTM
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))

# Build LSTM model
model = Sequential([
    LSTM(50, return_sequences=True, input_shape=(x_train.shape[1], 1)),
    Dropout(0.2),

    LSTM(50, return_sequences=True),
    Dropout(0.2),

    LSTM(50),
    Dropout(0.2),

    Dense(1)
])

# Compile model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train model
model.fit(x_train, y_train, epochs=25, batch_size=32)

# Prepare test data
test_data = scaled_data[training_data_len - 60:]

x_test = []
y_test = df.iloc[training_data_len:]['Close'].values

for i in range(60, len(test_data)):
    x_test.append(test_data[i-60:i, 0])

x_test = np.array(x_test)

# Reshape test data
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))

# Predictions
predictions = model.predict(x_test)
predictions = scaler.inverse_transform(predictions)

# Plot results
plt.figure(figsize=(16, 8))
plt.title('Google Stock Prices - Predicted vs Actual')

plt.plot(df.iloc[training_data_len:].index, y_test, label='Actual')
plt.plot(df.iloc[training_data_len:].index, predictions, label='Predicted')

plt.xlabel('Date')
plt.ylabel('Close Price USD ($)')
plt.legend()
plt.show()

!jupyter nbconvert --to html "/content/Recurrent_neural_network_(RNN).ipynb"